### ISSUE TITLE
The plugin doesnt work

### ISSUE THREAD

**Issue by Visivel** [InsiderAnh/XPlayerKits#2]
when executing /kits (or /xplayerkits:kits), it does nothing and when executing /xkits editor, it prompt this error:

edit: i also tried to install nbtapi, the error persists)

```
18:55:54 INFO]: Visivel issued server command: /xkits editor
[18:55:54 ERROR]: Command exception: /xkits editor
org.bukkit.command.CommandException: Unhandled exception executing command 'xkits' in plugin XPlayerKits v1.0.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2297) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2271) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.github.InsiderAnh.xPlayerKits.libs.nbtapi.NBTReflectionUtil
	at xPlayerKits.jar/io.github.InsiderAnh.xPlayerKits.libs.nbtapi.NBTCompound.setString(NBTCompound.java:176) ~[xPlayerKits.jar:?]
	at xPlayerKits.jar/io.github.InsiderAnh.xPlayerKits.utils.XPKUtils.applySimpleTag(XPKUtils.java:123) ~[xPlayerKits.jar:?]
	at xPlayerKits.jar/io.github.InsiderAnh.xPlayerKits.menus.MainKitEditorMenu.onUpdate(MainKitEditorMenu.java:76) ~[xPlayerKits.jar:?]
	at xPlayerKits.jar/io.github.InsiderAnh.xPlayerKits.inventory.AInventory.open(AInventory.java:108) ~[xPlayerKits.jar:?]
	at xPlayerKits.jar/io.github.InsiderAnh.xPlayerKits.commands.XKitsCommands.onCommand(XKitsCommands.java:57) ~[xPlayerKits.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	... 27 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
	at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328) ~[?:?]
	at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242) ~[?:?]
	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097) ~[?:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:79) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at xPlayerKits.jar/io.github.InsiderAnh.xPlayerKits.libs.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59) ~[xPlayerKits.jar:?]
	at xPlayerKits.jar/io.github.InsiderAnh.xPlayerKits.libs.nbtapi.NBTCompound.setString(NBTCompound.java:176) ~[xPlayerKits.jar:?]
	at xPlayerKits.jar/io.github.InsiderAnh.xPlayerKits.utils.XPKUtils.applySimpleTag(XPKUtils.java:123) ~[xPlayerKits.jar:?]
	at xPlayerKits.jar/io.github.InsiderAnh.xPlayerKits.menus.MainKitEditorMenu.onUpdate(MainKitEditorMenu.java:76) ~[xPlayerKits.jar:?]
	at xPlayerKits.jar/io.github.InsiderAnh.xPlayerKits.inventory.AInventory.open(AInventory.java:108) ~[xPlayerKits.jar:?]
	at xPlayerKits.jar/io.github.InsiderAnh.xPlayerKits.commands.XKitsCommands.onCommand(XKitsCommands.java:57) ~[xPlayerKits.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	... 27 more
```

**Comment by InsiderAnh** [comment]
Whis is version not support, but i already added support.
